id = "dot"
name = "DOT"
version = "0.0.1"
schema_version = 1
authors = ["Yan Maciel"]
description = "Dot language support."
# repository = "https://github.com/your-name/my-zed-extension"

[grammars.dot]
repository = "https://github.com/rydesun/tree-sitter-dot"
commit = "9ab85550c896d8b294d9b9ca1e30698736f08cea"
